Improvements to 1010 backup and restore.  Exit if can't adb root, upload backup file to backblaze, etc.

diff --git a/backup-1010 b/backup-1010
--- a/backup-1010
+++ b/backup-1010
@@ -30,18 +30,7 @@ d=`date +%Y%m%d%H%M`
 mkdir $d
 cd $d
 
-adb root >/dev/null
-
-#adb pull /mnt/runtime/full/emulated/0/Android/obb/com.gramgames.tenten 1
-#adb pull /mnt/runtime/full/emulated/0/Android/data/com.gramgames.tenten 2
-#adb pull /mnt/runtime/write/emulated/0/Android/obb/com.gramgames.tenten 3
-#adb pull /mnt/runtime/write/emulated/0/Android/data/com.gramgames.tenten 4
-#adb pull /mnt/runtime/read/emulated/0/Android/obb/com.gramgames.tenten 5
-#adb pull /mnt/runtime/read/emulated/0/Android/data/com.gramgames.tenten 6
-#adb pull /mnt/runtime/default/emulated/0/Android/obb/com.gramgames.tenten 7
-#adb pull /mnt/runtime/default/emulated/0/Android/data/com.gramgames.tenten 8
-#adb pull /mnt/pass_through/0/emulated/0/Android/obb/com.gramgames.tenten 9
-#adb pull /mnt/pass_through/0/emulated/0/Android/data/com.gramgames.tenten 10
+adb root >/dev/null || { echo "Can't adb root -- is device connected?"; exit 1; }
 
 adb pull /data/misc/profiles/cur/0/com.gramgames.tenten 11
 adb pull /data/misc/profiles/ref/com.gramgames.tenten 12
@@ -49,21 +38,12 @@ adb pull /data/data/com.google.android.gms/files/backup_chunk_listings/com.gramg
 adb pull /data/data/com.gramgames.tenten 14
 adb pull /data/data/com.gramgames.tenten/shared_prefs/com.gramgames.tenten_preferences.xml 15
 adb pull /data/data/com.gramgames.tenten/shared_prefs/com.gramgames.tenten.v2.playerprefs.xml 16
-#adb pull /data/app/~~MCCwq4mx3eVwlBgOnl0HXw==/com.gramgames.tenten-imNUl4sBdFaCBB0-jV84fA== 17
 adb pull /data/system/graphicsstats/1626307200000/com.gramgames.tenten 18
 adb pull /data/user/0/com.google.android.gms/files/backup_chunk_listings/com.gramgames.tenten 19
 adb pull /data/user/0/com.gramgames.tenten 20
 adb pull /data/user/0/com.gramgames.tenten/shared_prefs/com.gramgames.tenten_preferences.xml 21
 adb pull /data/user/0/com.gramgames.tenten/shared_prefs/com.gramgames.tenten.v2.playerprefs.xml 22
 adb pull /data/user_de/0/com.gramgames.tenten 23
-#adb pull /data/media/0/Android/obb/com.gramgames.tenten 24
-#adb pull /data/media/0/Android/data/com.gramgames.tenten 25
-#adb pull /data_mirror/cur_profiles/0/com.gramgames.tenten 26
-#adb pull /data_mirror/data_de/null/0/com.gramgames.tenten 27
-#adb pull /data_mirror/data_ce/null/0/com.google.android.gms/files/backup_chunk_listings/com.gramgames.tenten 28
-#adb pull /data_mirror/data_ce/null/0/com.gramgames.tenten 29
-#adb pull /data_mirror/data_ce/null/0/com.gramgames.tenten/shared_prefs/com.gramgames.tenten_preferences.xml 30
-#adb pull /data_mirror/data_ce/null/0/com.gramgames.tenten/shared_prefs/com.gramgames.tenten.v2.playerprefs.xml 31
 
 cd ..
 
@@ -72,24 +52,15 @@ rm -rf $d
 
 set_tdiff
 
-#echo "Backed up to $d.tgz in $tdiff"
-#ls -alh "$d.tgz"
-
-echo "Completed backup in $tdiff"
+echo -e "\e[92m✔ Completed backup in $tdiff.\e[0m"
 du -h "$d.tgz"
 
-# Attempting pzipped backup at 128975 @ 12:21-ish AM, now techically Saturday, July 17
+b2 upload-file josiahbarber "$d.tgz" "$d.tgz"
 
-# Seemed to work!  And much faster and smaller backup file.  Let's try a few times before feeling confident.
-
-# Attempting compressed backup and restore again at 131620
-# (Note, I cleared cache before restore... don't know if that's helpful, but just noting I did so, and it worked that time.)
-
-# Again seemed to work!
-
-# So I may well be backing up things I don't need (or possibly skipping things I *should* backup, but so far so good), and
-#  my system may be overkill, but here's what I do:
-
+# I may well be backing up things I don't need (or possibly skipping things I *should* backup, but so far so good),
+#  and my system may be overkill, but here's what I do:
+#
 # * For backup, I swipe the app away from the task swicher, but don't do anything else; no force stopping or anything.
 # * For restore, I swipe it away if it's there, then force stop it, then clear cache, then do restore.
+#
 # I guess I'll experiment at some point to see what of that might be skippable, for for now, this seems to work!
